BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[users] (
    [id] INT NOT NULL IDENTITY(1,1),
    [name] VARCHAR(63) NOT NULL,
    [email] VARCHAR(127) NOT NULL,
    [password] VARCHAR(127) NOT NULL,
    [birthDate] DATE NOT NULL,
    [createdAt] DATETIME NOT NULL CONSTRAINT [DF__users__createdAt__36B12243] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME NOT NULL CONSTRAINT [DF__users__updatedAt__37A5467C] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [PK__users__3213E83F7AE3F542] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
